version: '3'
services:
  http-proxy:
    build:
      context: ./aio
    networks:
       - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aio.rule=Host(`localhost`)"
      - "traefik.http.routers.aio.entrypoints=aio"
      - "traefik.port=4400"
    environment:
      - AIO_PROXY_HOST=0.0.0.0
      - AIO_PROXY_PORT=4400
      - POSTGREST_API_HOST=postgrest
      - POSTGREST_API_PORT=3000
networks:
    traefik:
        external:
            name: annuaire-entreprises-sirene-api_backendsiren
