version: '3'
services:
  http-proxy:
    build:
      context: ./aio
    networks:
       - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aio.rule=Host(`localhost`)"
      - "traefik.http.routers.aio.entrypoints=aio"
      - "traefik.port=4400"
networks:
    traefik:
        external:
            name: api-annuaire-entreprises_api
