version: '3.6'
services:
  db-green:
    build:
      context: ./db
      shm_size: '60gb'
    shm_size: '60gb'
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=sirene
      - POSTGRES_USER=sirene
      - POSTGRES_PASSWORD=sirene
    networks:
       - traefik
networks:
    traefik:
        external:
            name: api-annuaire-entreprises_api
