version: "3.3"

services:

  traefik:
    image: "traefik:v2.3"
    networks:
      - onlysearch
    container_name: "traefik-onlysearch"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.elastic.address=:9200"
      - "--entrypoints.aio.address=:4400"
    ports:
      - "9200:9200"
      - "4400:4400"
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
    onlysearch:
        driver: bridge
