version: "3.3"

services:

  traefik-onlysearch:
    image: "traefik:v2.3"
    networks:
      - traefik-onlysearch
    container_name: "traefik-onlysearch"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.elastic.address=:9300"
      - "--entrypoints.aio.address=:4500"
    ports:
      - "9300:9300"
      - "4500:4500"
      - "8091:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
    traefik-onlysearch:
        driver: bridge
