version: '3'
services:
  http-proxy:
    build:
      context: ./aio
    environment:
       - CURRENT_COLOR=green
       - NEXT_COLOR=blue
    networks:
       - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aio.rule=Host(`localhost`)"
      - "traefik.http.routers.aio.entrypoints=aio"
      - "traefik.port=4500"
    container_name: aio-green
networks:
    traefik:
        name: only-search_backendsiren
