host: 0.0.0.0
port: 4500

output_url_search: "http://postgrest:3000/rpc/get_unite_legale"
output_url_siren: "http://postgrest:3000/rpc/get_etablissements"
output_url_siret: "http://postgrest:3000/rpc/get_etablissement"
